name: DungeonsAndDiamonds
version: '1.0-SNAPSHOT'
main: org.randomlima.dungeonsanddiamonds.DungeonsAndDiamonds
api-version: '1.20'
commands:
  d4:
    description: Roll a d4.
    usage: /<command>
    permission: dnd
  d6:
    description: Roll a d6.
    usage: /<command>
    permission: dnd
  d8:
    description: Roll a d8.
    usage: /<command>
    permission: dnd
  d10:
    description: Roll a d10.
    usage: /<command>
    permission: dnd
  d12:
    description: Roll a d12.
    usage: /<command>
    permission: dnd
  d16:
    description: Roll a d16.
    usage: /<command>
    permission: dnd
  d20:
    description: Roll a d20.
    usage: /<command>
    permission: dnd
  character:
    description: Create a character
    usage: /<command>
    permission: dnd
